---
- hosts: ml-server
  become: yes
  tasks:

    - name: Bootstrap python
      raw: test -e usr/bin/python || (apt -y update && apt install -y python)
      
    - name: Update package index
      apt: update_cache=yes

    - name: Install needed packages
      apt: 
        name: [apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common]
        state: latest 
        update_cache: yes

    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
        state: present
    
    - name: Install docker
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: latest
        update_cache: yes
    
    - name: Get docker version
      command: docker -v
      register: docker_version
    
    - name: Check installation status
      debug:
        msg: "{{ docker_version.stdout_lines }}"
    
    - name: Pull container
      command: docker pull sakell/flask-api-torch:latest

    - name: Run container with port mapping
      command: docker run -d -p 5000:5000 sakell/flask-api-torch:latest
